language: perl
sudo: false

addons:
  apt:
    packages:
      - libmagic1

# remember need at least one install command, even if there are no
# prereqs, else travis will try to install deps using cpanm
# which is not what we want since this is a Dist::Zilla dist.
install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

script:
  - dzil test -v

